# Generated by Django 5.1.4 on 2025-06-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("used_cars", "0002_userimage_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="car",
            name="price",
        ),
        migrations.AddField(
            model_name="car",
            name="brand",
            field=models.CharField(default="Unknown", max_length=50),
        ),
        migrations.AddField(
            model_name="car",
            name="city",
            field=models.CharField(default="Unknown", max_length=50),
        ),
        migrations.AddField(
            model_name="car",
            name="engine_capacity_cc",
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name="car",
            name="fuel_type",
            field=models.CharField(default="Petrol", max_length=20),
        ),
        migrations.AddField(
            model_name="car",
            name="insurance_valid_till",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="is_accidental",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="car",
            name="is_modified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="car",
            name="km_driven",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="car",
            name="mileage_kmpl",
            field=models.FloatField(default=15.0),
        ),
        migrations.AddField(
            model_name="car",
            name="model",
            field=models.CharField(default="Unknown", max_length=50),
        ),
        migrations.AddField(
            model_name="car",
            name="negotiable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="car",
            name="number_of_owners",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="car",
            name="pincode",
            field=models.CharField(default="000000", max_length=10),
        ),
        migrations.AddField(
            model_name="car",
            name="pollution_certificate_valid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="car",
            name="rc_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="car",
            name="service_history_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="car",
            name="transmission",
            field=models.CharField(default="Manual", max_length=20),
        ),
        migrations.AddField(
            model_name="car",
            name="variant",
            field=models.CharField(default="Standard", max_length=50),
        ),
        migrations.AddField(
            model_name="car",
            name="year_of_manufacture",
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
