# Generated by Django 5.1.4 on 2025-06-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("used_cars", "0003_remove_car_created_at_remove_car_price_car_brand_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
