# Generated by Django 5.1.4 on 2025-06-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("used_cars", "0004_car_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="interested_users",
            field=models.IntegerField(default=0),
        ),
    ]
