# Generated by Django 5.1.4 on 2025-06-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("used_cars", "0005_car_interested_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="is_accidental",
        ),
        migrations.RemoveField(
            model_name="car",
            name="is_modified",
        ),
        migrations.RemoveField(
            model_name="car",
            name="negotiable",
        ),
        migrations.RemoveField(
            model_name="car",
            name="pollution_certificate_valid",
        ),
        migrations.RemoveField(
            model_name="car",
            name="service_history_available",
        ),
        migrations.AddField(
            model_name="car",
            name="state",
            field=models.CharField(default="Unknown", max_length=50),
        ),
    ]
