# Generated by Django 5.1.4 on 2025-06-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("used_cars", "0007_alter_car_rc_available_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
