# Generated by Django 5.1.4 on 2025-06-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("used_cars", "0009_timeslot_booking_availableslot"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="car_number",
            field=models.CharField(
                blank=True, default="Unknown", max_length=15, null=True
            ),
        ),
    ]
