# Generated by Django 5.1.4 on 2025-06-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("used_cars", "0010_car_car_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_number",
            field=models.CharField(default="Unknown", max_length=15, unique=True),
        ),
    ]
